// apps/ui-react/src/features/configurations/components/ScraperForm.tsx
import { useState, useEffect } from 'react';
import {
  Box, Card, CardHeader, CardContent, TextField, Select, MenuItem,
  FormControlLabel, Switch, Button, Typography, Chip, InputBase,
  Divider, CircularProgress, FormControl, InputLabel,
} from '@mui/material';
import SaveIcon from '@mui/icons-material/Save';
import type { ScraperProfile } from '../../../core/models/scraper.model';
import { useUpdateProfile } from '../../../core/hooks/useScraper';
import { SOURCE_CATEGORIES, ALL_SOURCES, type ArrayField } from '../../../core/constants/scraper.const';

function ChipInput({
  label, hint, placeholder, value, onChange,
}: Readonly<{
  label: string;
  hint: string;
  placeholder?: string;
  value: string[];
  onChange: (v: string[]) => void;
}>) {
  const [input, setInput] = useState('');

  const add = (val: string) => {
    const trimmed = val.trim().toLowerCase();
    if (trimmed && !value.includes(trimmed)) onChange([...value, trimmed]);
    setInput('');
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' || e.key === ',') {
      e.preventDefault();
      add(input);
    }
  };

  return (
    <Box>
      <Typography variant="body2" color="text.secondary" sx={{ mb: 0.5 }}>{label}</Typography>
      <Box sx={{
        display: 'flex', flexWrap: 'wrap', gap: 0.5,
        border: 1, borderColor: 'divider', borderRadius: 1, p: 1, mb: 0.5,
      }}>
        {value.map(chip => (
          <Chip
            key={chip}
            label={chip}
            size="small"
            onDelete={() => onChange(value.filter(v => v !== chip))}
          />
        ))}
        <InputBase
          placeholder={placeholder}
          value={input}
          onChange={e => setInput(e.target.value)}
          onKeyDown={handleKeyDown}
          onBlur={() => { if (input.trim()) add(input); }}
          sx={{ flexGrow: 1, minWidth: 120, fontSize: 14 }}
        />
      </Box>
      <Typography variant="caption" color="text.secondary">{hint}</Typography>
    </Box>
  );
}

interface ScraperFormProps {
  profile: ScraperProfile;
  onProfileUpdated: (profile: ScraperProfile) => void;
}

export default function ScraperForm({ profile, onProfileUpdated }: Readonly<ScraperFormProps>) {
  const updateProfile = useUpdateProfile();

  const [chips, setChips] = useState<Record<ArrayField, string[]>>({
    searchTerms: [...profile.searchTerms],
    strongKeywords: [...profile.strongKeywords],
    additionalKeywords: [...profile.additionalKeywords],
    excludeTitle: [...profile.excludeTitle],
    excludeKeywords: [...profile.excludeKeywords],
  });
  const [minSalary, setMinSalary] = useState(profile.minSalary);
  const [minScore, setMinScore] = useState(profile.minScore);
  const [remoteOnly, setRemoteOnly] = useState(profile.remoteOnly);
  const [requireStrongMatch, setRequireStrongMatch] = useState(profile.requireStrongMatch);
  const [enabledSources, setEnabledSources] = useState<string[]>(profile.enabledSources ?? [...ALL_SOURCES]);

  useEffect(() => {
    setChips({
      searchTerms: [...profile.searchTerms],
      strongKeywords: [...profile.strongKeywords],
      additionalKeywords: [...profile.additionalKeywords],
      excludeTitle: [...profile.excludeTitle],
      excludeKeywords: [...profile.excludeKeywords],
    });
    setMinSalary(profile.minSalary);
    setMinScore(profile.minScore);
    setRemoteOnly(profile.remoteOnly);
    setRequireStrongMatch(profile.requireStrongMatch);
    setEnabledSources(profile.enabledSources ?? [...ALL_SOURCES]);
  }, [profile.id]);

  const setChipField = (field: ArrayField, value: string[]) =>
    setChips(prev => ({ ...prev, [field]: value }));

  const toggleSource = (source: string, enabled: boolean) =>
    setEnabledSources(prev => enabled ? [...prev, source] : prev.filter(s => s !== source));

  const save = (e: React.FormEvent) => {
    e.preventDefault();
    updateProfile.mutate(
      { id: profile.id, minSalary, minScore, remoteOnly, requireStrongMatch, enabledSources, ...chips },
      { onSuccess: updated => onProfileUpdated(updated) },
    );
  };

  return (
    <Box component="form" onSubmit={save} sx={{ display: 'flex', flexDirection: 'column', gap: 3 }}>

      {/* Search Terms */}
      <Card>
        <CardHeader
          title="Search Terms"
          subheader="Each term is searched separately on LinkedIn and other platforms."
          slotProps={{ title: { variant: 'h6' } }}
        />
        <CardContent>
          <ChipInput
            label="Search Terms"
            placeholder="e.g. Senior Frontend Developer…"
            hint="Type a term and press Enter or , to add it. Click × to remove."
            value={chips.searchTerms}
            onChange={v => setChipField('searchTerms', v)}
          />
        </CardContent>
      </Card>

      {/* Filters */}
      <Card>
        <CardHeader title="Filters" titleTypographyProps={{ variant: 'h6' }} />
        <CardContent>
          <Box sx={{ display: 'flex', gap: 2, flexWrap: 'wrap', mb: 2 }}>
            <TextField
              label="Min Salary"
              type="number"
              size="small"
              value={minSalary}
              onChange={e => setMinSalary(Number(e.target.value))}
              slotProps={{ htmlInput: { min: 0 } }}
              sx={{ flex: '1 1 160px' }}
            />
            <FormControl size="small" sx={{ flex: '1 1 160px' }}>
              <InputLabel>Min Score</InputLabel>
              <Select label="Min Score" value={minScore} onChange={e => setMinScore(Number(e.target.value))}>
                {[1, 2, 3, 4, 5].map(p => (
                  <MenuItem key={p} value={p}>{'★'.repeat(p)}</MenuItem>
                ))}
              </Select>
            </FormControl>
          </Box>
          <Box sx={{ display: 'flex', gap: 3 }}>
            <FormControlLabel
              control={<Switch checked={remoteOnly} onChange={e => setRemoteOnly(e.target.checked)} color="primary" />}
              label="Remote Only"
            />
            <FormControlLabel
              control={<Switch checked={requireStrongMatch} onChange={e => setRequireStrongMatch(e.target.checked)} color="primary" />}
              label="Require Strong Match"
            />
          </Box>
        </CardContent>
      </Card>

      {/* Keywords */}
      <Card>
        <CardHeader
          title="Keywords"
          subheader="Used to score and rank jobs by relevance."
          slotProps={{ title: { variant: 'h6' } }}
        />
        <CardContent sx={{ display: 'flex', flexDirection: 'column', gap: 2.5 }}>
          <ChipInput
            label="Strong Keywords"
            placeholder="e.g. TypeScript, React…"
            hint="Jobs matching these keywords get a higher relevance score. Press Enter or , to add."
            value={chips.strongKeywords}
            onChange={v => setChipField('strongKeywords', v)}
          />
          <ChipInput
            label="Additional Keywords"
            placeholder="e.g. GraphQL, Node.js…"
            hint="Secondary keywords — still boost score, but less than strong keywords."
            value={chips.additionalKeywords}
            onChange={v => setChipField('additionalKeywords', v)}
          />
        </CardContent>
      </Card>

      {/* Exclusions */}
      <Card>
        <CardHeader
          title="Exclusions"
          subheader="Jobs matching these will be filtered out before saving."
          slotProps={{ title: { variant: 'h6' } }}
        />
        <CardContent sx={{ display: 'flex', flexDirection: 'column', gap: 2.5 }}>
          <ChipInput
            label="Exclude by Job Title"
            placeholder="e.g. junior, intern, manager…"
            hint="Jobs whose title contains any of these words will be skipped. Press Enter or , to add."
            value={chips.excludeTitle}
            onChange={v => setChipField('excludeTitle', v)}
          />
          <ChipInput
            label="Exclude by Description Keyword"
            placeholder="e.g. WordPress, Ruby, Golang…"
            hint="Jobs whose description contains these words will be skipped."
            value={chips.excludeKeywords}
            onChange={v => setChipField('excludeKeywords', v)}
          />
        </CardContent>
      </Card>

      {/* Platforms */}
      <Card>
        <CardHeader title="Scraper Platforms" titleTypographyProps={{ variant: 'h6' }} />
        <CardContent>
          <Typography variant="caption" color="text.secondary" sx={{ display: 'block', mb: 1.5 }}>
            Toggle which platforms are scraped during each run.
          </Typography>
          {SOURCE_CATEGORIES.map((category, idx) => (
            <Box key={category.label}>
              <Typography variant="body2" sx={{ fontWeight: 500, color: 'text.secondary', mb: 1, mt: idx === 0 ? 0 : 0.5 }}>
                {category.label}
              </Typography>
              <Box sx={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(160px, 1fr))', gap: 1.5, mb: 2 }}>
                {category.sources.map(source => (
                  <FormControlLabel
                    key={source}
                    control={
                      <Switch
                        size="small"
                        checked={enabledSources.includes(source)}
                        onChange={e => toggleSource(source, e.target.checked)}
                        color="primary"
                      />
                    }
                    label={<Typography variant="body2">{source}</Typography>}
                  />
                ))}
              </Box>
              {idx < SOURCE_CATEGORIES.length - 1 && <Divider sx={{ mb: 1.5 }} />}
            </Box>
          ))}
        </CardContent>
      </Card>

      {/* Save */}
      <Box sx={{ display: 'flex', justifyContent: 'flex-end', pb: 2 }}>
        <Button
          type="submit"
          variant="contained"
          startIcon={updateProfile.isPending ? <CircularProgress size={18} color="inherit" /> : <SaveIcon />}
          disabled={updateProfile.isPending}
        >
          Save Changes
        </Button>
      </Box>

    </Box>
  );
}

// apps/ui/src/app/features/settings/components/scraper-form.component.ts
import { Component, inject, signal, input, output, effect, DestroyRef } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { FormsModule } from '@angular/forms';
import { COMMA, ENTER } from '@angular/cdk/keycodes';
import { MatChipInputEvent, MatChipsModule } from '@angular/material/chips';
import { MatCardModule } from '@angular/material/card';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { MatSlideToggleModule } from '@angular/material/slide-toggle';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatDividerModule } from '@angular/material/divider';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { ScraperProfileService } from '@core/services/scraper-profile.service';
import { ToastService } from '@core/services/toast.service';
import { ScraperProfile } from '@core/models/scraper-profile.model';
import { ArrayField, ALL_SOURCES, SOURCE_CATEGORIES } from '@core/constants/scraper.const';

@Component({
  selector: 'app-scraper-form',
  imports: [
    ReactiveFormsModule, FormsModule,
    MatCardModule, MatFormFieldModule, MatInputModule, MatSelectModule,
    MatChipsModule, MatSlideToggleModule, MatButtonModule,
    MatIconModule, MatDividerModule, MatProgressSpinnerModule,
  ],
  template: `
    <form [formGroup]="form" (ngSubmit)="save()" class="overflow-x-hidden">

      <!-- Search Terms -->
      <mat-card class="mb-5">
        <mat-card-header>
          <mat-card-title>Search Terms</mat-card-title>
          <mat-card-subtitle>Each term is searched separately on LinkedIn and other platforms.</mat-card-subtitle>
        </mat-card-header>
        <mat-card-content class="!pt-3">
          <div class="field-wrap">
            <mat-form-field appearance="outline" class="w-full">
              <mat-label>Search Terms</mat-label>
              <mat-chip-grid #searchGrid class="w-full">
                @for (term of chips['searchTerms'](); track term) {
                  <mat-chip-row (removed)="removeChip('searchTerms', term)">
                    {{ term }}<button matChipRemove><mat-icon>cancel</mat-icon></button>
                  </mat-chip-row>
                }
                <input placeholder="e.g. Senior Frontend Developer…"
                  [matChipInputFor]="searchGrid"
                  [matChipInputSeparatorKeyCodes]="separatorKeys"
                  (matChipInputTokenEnd)="addChip('searchTerms', $event)" />
              </mat-chip-grid>
              <mat-hint>Type a term and press <kbd class="kbd">Enter</kbd> or <kbd class="kbd">,</kbd> to add it. Click × to remove.</mat-hint>
            </mat-form-field>
          </div>
        </mat-card-content>
      </mat-card>

      <!-- Filters -->
      <mat-card class="mb-5">
        <mat-card-header><mat-card-title>Filters</mat-card-title></mat-card-header>
        <mat-card-content class="!pt-3">
          <div class="flex gap-4 flex-wrap mb-3">
            <mat-form-field appearance="outline" class="flex-1 min-w-[160px]">
              <mat-label>Min Salary</mat-label>
              <input matInput type="number" formControlName="minSalary" min="0">
            </mat-form-field>
            <mat-form-field appearance="outline" class="flex-1 min-w-[160px]">
              <mat-label>Min Score</mat-label>
              <mat-select formControlName="minScore">
                @for (p of [1,2,3,4,5]; track p) {
                  <mat-option [value]="p">{{ '★'.repeat(p) }}</mat-option>
                }
              </mat-select>
            </mat-form-field>
          </div>
          <div class="flex gap-6 items-center py-1">
            <mat-slide-toggle formControlName="remoteOnly" color="primary">Remote Only</mat-slide-toggle>
            <mat-slide-toggle formControlName="requireStrongMatch" color="primary">Require Strong Match</mat-slide-toggle>
          </div>
        </mat-card-content>
      </mat-card>

      <!-- Keywords -->
      <mat-card class="mb-5">
        <mat-card-header>
          <mat-card-title>Keywords</mat-card-title>
          <mat-card-subtitle>Used to score and rank jobs by relevance.</mat-card-subtitle>
        </mat-card-header>
        <mat-card-content class="!pt-3">
          <div class="field-wrap">
            <mat-form-field appearance="outline" class="w-full">
              <mat-label>Strong Keywords</mat-label>
              <mat-chip-grid #strongGrid class="w-full">
                @for (kw of chips['strongKeywords'](); track kw) {
                  <mat-chip-row (removed)="removeChip('strongKeywords', kw)">
                    {{ kw }}<button matChipRemove><mat-icon>cancel</mat-icon></button>
                  </mat-chip-row>
                }
                <input placeholder="e.g. TypeScript, React…"
                  [matChipInputFor]="strongGrid"
                  [matChipInputSeparatorKeyCodes]="separatorKeys"
                  (matChipInputTokenEnd)="addChip('strongKeywords', $event)" />
              </mat-chip-grid>
              <mat-hint>Jobs matching these keywords get a higher relevance score. Press <kbd class="kbd">Enter</kbd> or <kbd class="kbd">,</kbd> to add.</mat-hint>
            </mat-form-field>
          </div>
          <div class="field-wrap">
            <mat-form-field appearance="outline" class="w-full">
              <mat-label>Additional Keywords</mat-label>
              <mat-chip-grid #additionalGrid class="w-full">
                @for (kw of chips['additionalKeywords'](); track kw) {
                  <mat-chip-row (removed)="removeChip('additionalKeywords', kw)">
                    {{ kw }}<button matChipRemove><mat-icon>cancel</mat-icon></button>
                  </mat-chip-row>
                }
                <input placeholder="e.g. GraphQL, Node.js…"
                  [matChipInputFor]="additionalGrid"
                  [matChipInputSeparatorKeyCodes]="separatorKeys"
                  (matChipInputTokenEnd)="addChip('additionalKeywords', $event)" />
              </mat-chip-grid>
              <mat-hint>Secondary keywords — still boost score, but less than strong keywords.</mat-hint>
            </mat-form-field>
          </div>
        </mat-card-content>
      </mat-card>

      <!-- Exclusions -->
      <mat-card class="mb-5">
        <mat-card-header>
          <mat-card-title>Exclusions</mat-card-title>
          <mat-card-subtitle>Jobs matching these will be filtered out before saving.</mat-card-subtitle>
        </mat-card-header>
        <mat-card-content class="!pt-3">
          <div class="field-wrap">
            <mat-form-field appearance="outline" class="w-full">
              <mat-label>Exclude by Job Title</mat-label>
              <mat-chip-grid #excludeTitleGrid class="w-full">
                @for (kw of chips['excludeTitle'](); track kw) {
                  <mat-chip-row (removed)="removeChip('excludeTitle', kw)">
                    {{ kw }}<button matChipRemove><mat-icon>cancel</mat-icon></button>
                  </mat-chip-row>
                }
                <input placeholder="e.g. junior, intern, manager…"
                  [matChipInputFor]="excludeTitleGrid"
                  [matChipInputSeparatorKeyCodes]="separatorKeys"
                  (matChipInputTokenEnd)="addChip('excludeTitle', $event)" />
              </mat-chip-grid>
              <mat-hint>Jobs whose title contains any of these words will be skipped. Press <kbd class="kbd">Enter</kbd> or <kbd class="kbd">,</kbd> to add.</mat-hint>
            </mat-form-field>
          </div>
          <div class="field-wrap">
            <mat-form-field appearance="outline" class="w-full">
              <mat-label>Exclude by Description Keyword</mat-label>
              <mat-chip-grid #excludeKwGrid class="w-full">
                @for (kw of chips['excludeKeywords'](); track kw) {
                  <mat-chip-row (removed)="removeChip('excludeKeywords', kw)">
                    {{ kw }}<button matChipRemove><mat-icon>cancel</mat-icon></button>
                  </mat-chip-row>
                }
                <input placeholder="e.g. WordPress, Ruby, Golang…"
                  [matChipInputFor]="excludeKwGrid"
                  [matChipInputSeparatorKeyCodes]="separatorKeys"
                  (matChipInputTokenEnd)="addChip('excludeKeywords', $event)" />
              </mat-chip-grid>
              <mat-hint>Jobs whose description contains these words will be skipped.</mat-hint>
            </mat-form-field>
          </div>
        </mat-card-content>
      </mat-card>

      <!-- Platforms -->
      <mat-card class="mb-5">
        <mat-card-header><mat-card-title>Scraper Platforms</mat-card-title></mat-card-header>
        <mat-card-content>
          <p class="text-xs text-slate-400 mb-3">Toggle which platforms are scraped during each run.</p>
          @for (category of sourceCategories; track category.label) {
            <p class="text-sm font-medium text-slate-500 mb-2 mt-1">{{ category.label }}</p>
            <div class="grid grid-cols-[repeat(auto-fill,minmax(160px,1fr))] gap-3 mb-4">
              @for (source of category.sources; track source) {
                <mat-slide-toggle color="primary"
                  [checked]="enabledSources().includes(source)"
                  (change)="toggleSource(source, $event.checked)">
                  {{ source }}
                </mat-slide-toggle>
              }
            </div>
            @if (!$last) { <mat-divider class="!mb-4" /> }
          }
        </mat-card-content>
      </mat-card>

      <!-- Save -->
      <div class="flex justify-end pb-4">
        <button mat-flat-button color="primary" type="submit" [disabled]="saving()">
          <span class="flex items-center gap-1.5">
            @if (saving()) { <mat-spinner diameter="18" /> } @else { <mat-icon>save</mat-icon> }
            Save Changes
          </span>
        </button>
      </div>

    </form>
  `,
  styles: [`
    .field-wrap { display: block; width: 100%; min-width: 0; overflow: hidden; margin-bottom: 20px; padding-top: 10px; }
    .field-wrap:last-child { margin-bottom: 0; }
    .field-wrap mat-form-field { display: block; }
  `],
})
export class ScraperFormComponent {
  private readonly profileSvc = inject(ScraperProfileService);
  private readonly toast = inject(ToastService);
  private readonly fb = inject(FormBuilder);
  private readonly destroyRef = inject(DestroyRef);

  readonly profile = input.required<ScraperProfile>();
  readonly profileUpdated = output<ScraperProfile>();

  readonly separatorKeys = [ENTER, COMMA] as const;
  readonly sourceCategories = SOURCE_CATEGORIES;
  readonly saving = signal(false);
  readonly enabledSources = signal<string[]>([...ALL_SOURCES]);

  readonly chips: Record<ArrayField, ReturnType<typeof signal<string[]>>> = {
    searchTerms: signal([]),
    strongKeywords: signal([]),
    additionalKeywords: signal([]),
    excludeTitle: signal([]),
    excludeKeywords: signal([]),
  };

  readonly form = this.fb.group({
    minSalary: [0, [Validators.required, Validators.min(0)]],
    minScore: [2, [Validators.required, Validators.min(0)]],
    remoteOnly: [true],
    requireStrongMatch: [true],
  });

  constructor() {
    // Reset form whenever the profile input changes
    effect(() => {
      const p = this.profile();
      this.form.patchValue({
        minSalary: p.minSalary,
        minScore: p.minScore,
        remoteOnly: p.remoteOnly,
        requireStrongMatch: p.requireStrongMatch,
      });
      for (const field of Object.keys(this.chips) as ArrayField[]) {
        this.chips[field].set([...(p[field] as string[])]);
      }
      this.enabledSources.set(p.enabledSources ?? [...ALL_SOURCES]);
    });
  }

  addChip(field: ArrayField, event: MatChipInputEvent) {
    const value = (event.value ?? '').trim().toLowerCase();
    if (value && !this.chips[field]().includes(value)) {
      this.chips[field].update(arr => [...arr, value]);
    }
    event.chipInput.clear();
  }

  removeChip(field: ArrayField, item: string) {
    this.chips[field].update(arr => arr.filter(v => v !== item));
  }

  toggleSource(source: string, enabled: boolean) {
    this.enabledSources.update(list =>
      enabled ? [...list, source] : list.filter(s => s !== source),
    );
  }

  save() {
    if (this.form.invalid) return;
    this.saving.set(true);

    const payload: Partial<ScraperProfile> = {
      ...this.form.value as Partial<ScraperProfile>,
      searchTerms: this.chips['searchTerms'](),
      strongKeywords: this.chips['strongKeywords'](),
      additionalKeywords: this.chips['additionalKeywords'](),
      excludeTitle: this.chips['excludeTitle'](),
      excludeKeywords: this.chips['excludeKeywords'](),
      enabledSources: this.enabledSources(),
    };

    this.profileSvc.update(this.profile().id, payload).pipe(
      takeUntilDestroyed(this.destroyRef),
    ).subscribe({
      next: ({ profile }) => {
        this.profileUpdated.emit(profile);
        this.toast.success('Profile saved');
        this.saving.set(false);
      },
      error: () => this.saving.set(false),
    });
  }
}
